[project]
name = "futbolia-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.7",
    "fastapi>=0.127.0",
    "httpx>=0.28.1",
    "motor>=3.7.1",
    "openai>=2.14.0",
    "passlib>=1.7.4",
    "pyjwt>=2.10.1",
    "uvicorn>=0.40.0",
]
